"""fix updated_at default for recipe

Revision ID: 15da45ec5e9e
Revises: 2dabdc4fc144
Create Date: 2025-07-28 11:05:01.251546

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "15da45ec5e9e"
down_revision: Union[str, Sequence[str], None] = "2dabdc4fc144"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
